<?php

require_once '../model/connection.php';
//RW line 5-6
require_once 'View/myBlog.php';
require_once 'Model/upload.php';

if (isset ($_POST['btn-post'])){
//getting rid of whitespace
    $title     = trim($_POST['title']);
    $content   = trim($_POST['content']);
   // $tags      = trim($_POST['tags']);

if (empty ($title)){
        
        $error[] = "Please enter a title."; 
    }
    
    if (empty($content)) {

        $error[] = "Please enter some text.";
    } 
    
    if (strlen($title) > 250) {
    $errors = 'Please shorten your title, it is too long (250 character limit).';
    }
    
    if (strlen($content) > 2000) {
    $errors = 'Please shorten your blog post, it is too long (2000 character limit).';
    }

    else {
        $post->newPost($title, $content);
    }
}

?>

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        
        <style> 
            label {display: block}
        </style>
        
        <title> Add Post </title>
    </head>

    <body>
        <div class="container">
        <button class="btn btn-secondary col-sm-4" type="button" data-toggle="collapse" data-target="#post" aria-expanded="false" aria-controls="collapseExample">
            New Post</button><br><br><br>
        
        <?php
        //gives a list of errors under 'Add Post' heading, if user makes an error
        if ( isset($errors) && ! empty($errors)){
            echo '<ul><li>', implode('</li><li>', $errors), '</li></ul>';
        }
        ?>
       <div id="post" class="collapse">
        
           <form class ="col-sm-8 well well-lg" action="" method="post">
                    
            <div class="form-group">
                <label for="title">Title</label>
                <input class="form-control" type="text" name="title" value="<?php if ( isset($_POST['title']) ) echo $_POST['title']; ?>">
            </div>
            
            <div class="form-group" action="upload.php" method="post" enctype="multipart/form-data">
                Select image to upload:
                <label for="image">Image</label>
                <input type="file" name="fileToUpload" id="fileToUpload">
                <input type="submit" value="Upload Image" name="submit">
                <!-- <input type="image" name="image" value=" <?php //if ( isset($_POST['image']) ) echo $_POST['image']; ?>"> -->
            </div>
                    
            
            <div class="form-group">
                <label for="content"> Content </label>
                <textarea class="form-control" name="content" rows="10"><?php if ( isset($_POST['content']) ) echo $_POST['content']; ?></textarea>
            </div>
            
            <div class="form-group">
                <label for="musicplayer"> Music Player </label>
                <input type="text" name="musicplayer"></input> 
            </div>
            
            <div class="form-group">
                <label for="tags"> Tags </label>
                <textarea class="form-control" name="tags" rows="1"></textarea>
                </div>
                <?php
                //foreach ( get_tags() as $tags ) {
                    ?>
                <!-- this is if we are to use a drop down of prexisting tags -->
                <option value ="<?php echo $tags['id']; ?>"><?php echo $tags['name']; ?></option>
                <?php

                ?>
                
                <div>
                <input type="submit" value="Add Post" name="btn-post">
                </div>
                       </form>
            </div>
 
        </div>

    </body>
</html>