<?php

require_once '../model/connection.php';

//The below should be redundant as long as the button is pushed. 
//$_POST['title'], $_POST['content'], $_POST['tags'], $_POST['musicplayer'], $_POST['image'] 

if (isset ($_POST['btn-post'])){
//getting rid of whitespace
    $title     = trim($_POST['title']);
    $content   = trim($_POST['content']);
   // $tags      = trim($_POST['tags']);

if (empty ($title)){
        
        $error[] = "Please enter a title."; 
    }
    
    if (empty($content)) {

        $error[] = "Please enter some text.";
    } 
    
    if (strlen($title) > 250) {
    $errors = 'Please shorten your title, it is too long (250 character limit).';
    }
    
    if (strlen($content) > 2000) {
    $errors = 'Please shorten your blog post, it is too long (2000 character limit).';
    }

    else {
        $post->newPost($title, $content);
    }
}




?>

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        
        <style> 
            label {display: block}
        </style>
        
        <title> Add Post </title>
    </head>

    <body>
        <h1> Add Post </h1>
        
        <?php
        //gives a list of errors under 'Add Post' heading, if user makes an error
        if ( isset($errors) && ! empty($errors)){
            echo '<ul><li>', implode('</li><li>', $errors), '</li></ul>';
        }
        ?>
        
        <form action="" method="post">
            
            <div>
                <label for="title">Title</label>
                <input type="text" name="title" value="<?php if ( isset($_POST['title']) ) echo $_POST['title']; ?>">
            </div>
            
            <div>
                <label for="image">Image</label>
                <input type="image" name="title" value="<?php if ( isset($_POST['image']) ) echo $_POST['image']; ?>">                
            </div>
            
            <div>
                <label for="content"> Content </label>
                <textarea name="content" rows="15" cols="50"><?php if ( isset($_POST['content']) ) echo $_POST['content']; ?></textarea>
            </div>
            
            <div>
                <label for="musicplayer"> Music Player </label>
                <select name="musicplayer"></select>
            </div>
            
            <div>
                <label for="tags"> Tags </label>
                <select name="tags"></select>
                <?php
                //foreach ( get_tags() as $tags ) {
                    ?>
                <!-- this is if we are to use a drop down of prexisting tags -->
                <option value ="<?php echo $tags['id']; ?>"><?php echo $tags['name']; ?></option>
                <?php
                
                ?>
                
            </div>
            
            <div>
                <input type="submit" value="Add Post" name="btn-post">
            </div>
           
        </form>
    </body>
</html>
