<?php

//require_once '../model/connection.php';
//RW line 5-6
//require_once 'View/myBlog.php';
//include 'upload.php';



?>

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        
        <style> 
            label {display: block}
        </style>
        
        <title> Add Post </title>
    </head>

    <body>
        <div class="container">
        <button class="btn btn-secondary col-sm-4" type="button" data-toggle="collapse" data-target="#post" aria-expanded="false" aria-controls="collapseExample">
            New Post</button><br><br><br>
        
        <?php
        //gives a list of errors under 'Add Post' heading, if user makes an error
        if ( isset($errors) && ! empty($errors)){
            echo '<ul><li>', implode('</li><li>', $errors), '</li></ul>';
        }
        ?>
       <div id="post" class="collapse">
        
           <form class ="col-sm-8 well well-lg" action="" method="post" enctype="multipart/form-data">
                
            <div class="form-group">
                <label for="title">Title</label>
                <input class="form-control" type="text" name="title" value="<?php if ( isset($_POST['title']) ) echo $_POST['title']; ?>">
            </div>
            
          
                    
            
            <div class="form-group">
                <label for="content"> Content </label>
                <textarea class="form-control" name="content" rows="10"><?php if ( isset($_POST['content']) ) echo $_POST['content']; ?></textarea>
            </div>
            
               <div class='form-group'>
                 
                <label for="image">Image</label>
                <input type='file' name='image'/>
                <!--<input type="submit" value="Upload Image" name="btn-img">-->
               </div>
               
               
            <!--<div class="form-group">
                <label for="musicplayer"> Music Player </label>
                <input type="text" name="musicplayer"></input> 
            </div>-->
            
            <div class="form-group">
                <label for="tags"> Tags </label>
                <textarea class="form-control" name="tags" rows="1"><?php if ( isset($_POST['tags']) ) echo $_POST['tags']; ?></textarea>
            </div>
                <?php
                //foreach ( get_tags() as $tags ) {
                    ?>
                <!-- this is if we are to use a drop down of prexisting tags -->
                <option value ="<?php //echo $tags['id']; ?>"><?php //echo $tags['name']; ?></option>
                <?php

                ?>
                
                <div>
                <input type="submit" value="Add Post" name="btn-post">
                </div>
                       </form>
        
            </div>
 
        </div>

    </body>
</html>