<?php

require_once '../model/connection.php';
include 'userFunctions.php';

$thisID = filter_input(INPUT_GET, 'id',FILTER_SANITIZE_ENCODED);



?>

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        
        <style> 
            label {display: block}
        </style>
        
        <title> Add Post </title>
        
        <script>
            function confirmDeleteComment() {
                var txt;
                var r = confirm("Are you sure you want to delete this comment?");
                if (r == true) {
                    window.location.href='templates/comment_delete.php?id='+<?=$commentID ?>+'&post='+<?=$thisID?>;
                } else {
                    return false;
            }
        }
        </script>

    </head>

    <body>
                <form id="delete" method="post" action="">
        
                    <input type="button" class="btn btn-sm btn-danger" value="Delete" name="btn-com-delete"onclick="confirmDeleteComment();">   
                    
                </form>
    </body>
</html>
