<form class="form-horizontal" id="contact-form" method="post" action="send_form_email.php" role="form">

                <div class="col-md-12">
                    <div class="form-group">
                    <label class="control-label" for="first_name">Firstname </label>
                    <input id="form_name" type="text" name="name" class="form-control" placeholder="Firstname " required="required" data-error="Firstname is required.">
                    <div class="help-block with-errors"></div>
                </div>
                </div>
            
            
            
                <div class="col-md-12">
                    <div class="form-group">
                    <label class="control-label" for="last_name">Lastname </label>
                    <input id="form_lastname" type="text" name="surname" class="form-control" placeholder="Lastname " required="required" data-error="Lastname is required.">
                    <div class="help-block with-errors"></div>
                </div>
            </div>
        
       
            <div class="col-md-12">
                <div class="form-group">
                    <label for="form_email">Email </label>
                    <input id="form_email" type="email" name="email" class="form-control" placeholder="Email " required="required" data-error="Valid email is required.">
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            
        
            <div class="col-md-12">
                <div class="form-group">
                    <label for="form_message">Message </label>
                    <textarea id="form_message" name="message" class="form-control" placeholder="Message" rows="4" required="required" data-error="Please,leave us a message."></textarea>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <br>
            
        <div class="form-group col-sm-4">
                <button type="submit" class="btn btn-block btn-primary" value="Send message">
                    <i class="glyphicon glyphicon-open-file"></i>&nbsp;Send
                </button>
            </div>
        </div>
       
    </div>

</form>