<?php

require_once '../model/connection.php';
include 'userFunctions.php';

$thisID = filter_input(INPUT_GET, 'id',FILTER_SANITIZE_ENCODED);



?>

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        
        <style> 
            label {display: block}
        </style>
        
        <title> Add Post </title>
        
        <script>
            function confirmDelete() {
                var txt;
                var r = confirm("Are you sure you want to delete this post?");
                if (r == true) {
                    window.location.href='templates/delete_post.php?id='+<?=$thisID ?>;
                } else {
                    return false;
            }
        }
        </script>

    </head>

    <body>
                <form id="delete" method="post" action="">
                    
                    <input type="button" class="btn btn-warning" Value ="Update Post" name="btn-update" onclick="window.location.href='updatePost.php?id='+<?=$thisID ?>">
        
                    <input type="button" class="btn btn-danger" value="Delete" name="btn-delete"onclick="confirmDelete();">   
                    
                </form>
    </body>
</html>
