<?php
/*Creating a variable that calls the read all method in the post class. 
 * The read all method is based on reading the posts for the user that is currently logged in. (in the SESSION)
 * This code will then echo the Title, Content and Date Posted, in that order. 
 */
$posts = $post->readAll();

foreach($posts as $post):?>

<div class="panel panel-default">
  <div class="panel-heading">
      <a href="viewPost.php?id=<?= $post['post_id']; ?>"><b><?= htmlspecialchars($post['post_title']);?></b></a>
  </div>
    <div class="panel-body">
        
        <?php if($post['image'] != NULL) { ?>
        <a href="../model/blogimageuploads/<?=$post['image'];?>" target="_blank"><img src="../model/blogimageuploads/<?=$post['image'];?>" width="150" class="img-thumbnail img-responsive pull-left img-rightmargin" /></a>
        <?php } ?>
<?= htmlspecialchars($post['post_content']);?>
    </div>
    <div class='panel-footer'>
        <?php if($post['tags'] != ''){
            
            $tagsArray=explode(',',$post['tags']); 
            foreach ($tagsArray as $tag){
                ?> <a href="search.php?tag=<?= $tag; ?>"> <button type="button" class="btn btn-success btn-sm"><?= htmlspecialchars($tag); ?></button></a><?php echo " ";
            }
        }
        ?>
    </div>
</div>
<span class="badge"> 
<?= $post[3];?>
</span><br><br>
 
<?php endforeach; ?>