<?php
/*Creating a variable that calls the read all method in the post class. 
 * The read all method is based on reading the posts for the user that is currently logged in. (in the SESSION)
 * This code will then echo the Title, Content and Date Posted, in that order. 
 */
$posts = $post->readAll();

foreach($posts as $post):?>

<div class="panel panel-default">
  <div class="panel-heading">
      <a href="viewPost.php?id=<?= $post['post_id']; ?>"><b><?= $post['post_title'];?></b></a>
  </div>
    <div class="panel-body">
        
        <?php if($post['image'] != NULL) { ?>
        <a href="../Model/blogimageuploads/<?=$post['image'];?>" target="_blank"><img src="../Model/blogimageuploads/<?=$post['image'];?>" width="150" class="img-thumbnail img-responsive pull-left img-rightmargin" /></a>
        <?php } ?>
<?= $post['post_content'];?>
    </div>
</div>
<span class="badge"> 
<?= $post[3];?>
</span><br><br>
 
<?php endforeach; ?>