<?php
/*Creating a variable that calls the read all method in the post class. 
 * The read all method is based on reading the posts for the user that is currently logged in. (in the SESSION)
 * This code will then echo the Title, Content and Date Posted, in that order. 
 */
$posts = $post->readAll();

foreach($posts as $post):?>

<div class="panel panel-default">
  <div class="panel-heading">
<?= $post[1];?>
  </div>
    <div class="panel-body">
<?= $post[2];?>
    </div>
</div>
<span class="badge"> 
<?= $post[3];?>
</span><br><br>
 
<?php endforeach; ?>