<?php
/*Creating a variable that calls the read all method in the post class. 
 * The read all method is based on reading the posts for the user that is currently logged in. (in the SESSION)
 * This code will then echo the Title, Content and Date Posted, in that order. 
 */
$posts = $post->readAll();

foreach($posts as $post):?>
 
<h4>
<?= $post[1];?>
</h4>
<p>
<?= $post[2];?>
</p>
<p>
<?= $post[3];?>
</p>
<?php endforeach; ?>