<?php 
if(file_exists("../model/profileimageuploads/{$_SESSION['user_session']}.jpg")): ?>
		<img class='img-rounded img-responsive pull-left img-rightmargin' src="../model/profileimageuploads/<?=$_SESSION['user_session']?>.jpg" width="150" height="150" />
	<?php else: ?>
		<img class='img-rounded img-responsive pull-left img-rightmargin' src="../model/blogimages/defaultprofile.jpg" width="150" height="150" />
        <?php endif ?>