<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.php"><p class='tech'>Get Into Techno</p></a>
    </div>
          <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li><a href="index.php">Home</a></li>
      <li><a href="search.php">Search</a></li>
      <li><a href="myBlog.php">My Blog</a></li>
      <li><a href="settings.php">My Settings</a></li>
      <li><a href="contact.php">Contact</a></li>
      <?php if ($_SESSION['username'] == "Admin"){?>
      <li><a href="admin.php">Admin</a></li>
      <?php } ?>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Signed in as <?= $_SESSION['username'] ?></p></li>
      <li><a href="templates/logout.php"><span class="glyphicon glyphicon-log-in"></span> Log out</a></li>
    </ul>
          </div>
  </div>
</nav>