<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="index.php">Get Into Techno</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="index.php">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="register.php"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      
                    <form method= "post" class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" name="txt_uname_email" placeholder="Username or Email ID">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="txt_password" placeholder="Your Password">
                    </div>
                    <button type="submit" name="btn-login" class="btn btn-default">Sign In</button>
    </ul>
  </div>
</nav>