<?php
/*Creating a variable that calls the read user method in the post class. 
 * This method will bring up the posts for a certain tag based on the id provided from the get in the URL.
 * This code will then echo the Title, Content and Date Posted and tag name in that order. 
 */

$sanitizedTag = filter_input(INPUT_GET, 'tag',FILTER_SANITIZE_ENCODED);
$posts = $post->readTag($sanitizedTag);

foreach($posts as $post):?>
 
<h4>
<?= $post[1];?>
</h4>

<p>
<?= $post[2];?>
</p>

<p>
<?= $post[3];?>
</p>

<p>
<?= $post[4];?>
</p>

<p>
<?= $post[5];?>
</p>

<p>
<?= $post[6];?>
</p>

<?php endforeach; 

//why is 4 and 5 missing..? numbers are from uder posts = these can be changed to reflect tags to be diplayed
//RW - i've added four and 5
?>