<?php 
require_once '../model/connection.php';
include 'templates/userFunctions.php';



 $firstname = $_POST['first_name'];
 $lastname = $_POST['last_name'];
 $sessions = $_SESSION['user'];

  $sql = "UPDATE user_info SET first_name = '$firstname', last_name = '$lastname', WHERE username = '$sessions'";
  $result= mysql_query($sql);

  if($result){
  header("location:../settings_page.php");
  }

  else {
  echo error_reporting(E_ALL);
  } 

  
  mysql_close();
  ?>

  <div class="form-group">
                <label for="firstName"> Update First Name </label>
                <textarea class="form-control" name="firstName" rows="3"><?php if ( isset($_POST['firstName']) ) {echo $_POST['firstName'];} else {echo $thisUserFirstName;}; ?></textarea>
            </div>
        
                <div>
                <input type="submit" value="firstName" name="btn-firstName">
                </div>
                       </form>
            </div>
 
        </div>
        
        
  <div class="form-group">
                <label for="lastName"> Update Last Name </label>
                <textarea class="form-control" name="firstName" rows="3"><?php if ( isset($_POST['firstName']) ) {echo $_POST['firstName'];} else {echo $thisUserFirstName;}; ?></textarea>
            </div>
        
                <div>
                <input type="submit" value="firstName" name="btn-firstName">
                </div>
                       </form>
            </div>
 
        </div>