<?php 

require_once '../model/connection.php';
include 'templates/userFunctions.php';

 $email = $_POST['email'];
 $sessions = $_SESSION['user'];

  $sql = "UPDATE user_info SET email = '$email', WHERE username = '$sessions'";
  $result= mysql_query($sql);

  if($result){
  header("location:../settings_page.php");
  }

  else {
  echo error_reporting(E_ALL);
  } 



  
  
  mysql_close();
  ?>

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        
        <style> 
            label {display: block}
        </style>
        
        <title> Add bio </title>
    </head>
    
    <body

   <div class="form-group">
                <label for="email"> Update Email </label>
                <textarea class="form-control" name="email" rows="3"><?php if ( isset($_POST['email']) ) {echo $_POST['email'];} else {echo $thisUserEmail;}; ?></textarea>
            </div>
        
                <div>
                <input type="submit" value="Add Biography" name="btn-email">
                </div>
                       </form>
            </div>
 
        </div>
</body>   
</html>