<?php

require_once '../model/connection.php';
include 'userFunctions.php';


if (isset ($_POST['btn-post'])){
//getting rid of whitespace
    $title     = trim($_POST['title']);
    $content   = trim($_POST['content']);
    $ID = $postID;
   // $tags      = trim($_POST['tags']);

if (empty ($title)){
        
        $error[] = "Please enter a title."; 
    }
    
    if (empty($content)) {

        $error[] = "Please enter some text.";
    } 
    
    if (strlen($title) > 250) {
    $errors = 'Please shorten your title, it is too long (250 character limit).';
    }
    
    if (strlen($content) > 2000) {
    $errors = 'Please shorten your blog post, it is too long (2000 character limit).';
    }

    else {
        $post->updatePost($title, $content, $ID);
    }
}




?>

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        
        <style> 
            label {display: block}
        </style>
        
        <title> Add Post </title>
    </head>

    <body>
        
           
        <?php
        //gives a list of errors under 'Add Post' heading, if user makes an error
        if ( isset($errors) && ! empty($errors)){
            echo '<ul><li>', implode('</li><li>', $errors), '</li></ul>';
        }
        ?>
        <form class ="col-sm-8 well well-lg" action="" method="post">
            
            
            
            <div class="form-group">
                <label for="title">Title</label>
                <input class="form-control" type="text" name="title" value="<?= $postTitle ?>">
            </div>
            
            <div class="form-group">
                <label for="image">Image</label>
                <input type="image" name="title" value="<?php if ( isset($_POST['image']) ) echo $_POST['image']; ?>">                
            </div>
            
            <div class="form-group">
                <label for="content"> Content </label>
                <textarea class="form-control" name="content" rows="10"><?= $postContent ?></textarea>
            </div>
            
            <div class="form-group">
                <label for="musicplayer"> Music Player </label>
                <input type="text" name="musicplayer"></input>             
            </div>
            
            <div class="form-group">
                <label for="tags"> Tags </label>
                <textarea class="form-control" name="content" rows="1"></textarea>
                </div>
                <?php
                //foreach ( get_tags() as $tags ) {
                    ?>
                <!-- this is if we are to use a drop down of prexisting tags -->
                <option value ="<?php echo $tags['id']; ?>"><?php echo $tags['name']; ?></option>
                <?php
                
                ?>
                
                <div>
                <input type="submit" value="Update Post" name="btn-post">
                </div>
                       </form>
            
<?php print_r($_POST) ?>
    </body>
</html>
