<form class="form-horizontal" method='post'>
    <div class="form-group">
        <label class="control-label" for="biography">Update Biography:</label>
            <div>
                <textarea class="form-control col-sm-4" name='bio' rows='4' method='post'><?php echo $thisUserBio?></textarea>
            </div><br><br><hr/>
            <div class="form-group col-sm-6">
             <button type="submit" class="btn btn-block btn-primary" name="btn-bio" method='post'>
                 Update Bio
             </button></div>
            <div class="clearfix"></div><hr />
    </div>
</form>