<?php

//RW
require_once '../model/connection.php';

const image = 'myfile';
// Check if image file is a actual image or fake image
    if($_SERVER['REQUEST_METHOD'] == 'POST') {
        var_dump($_FILES);
        $target_dir = "../Model/blogimageuploads";
        $target_file = $target_dir . basename($_FILES[image]["name"]);
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file,PATHINFO_EXTENSION);
        $check = getimagesize($_FILES[image]["tmp_name"]);
        if($check !== false) {
            echo "File is an image - " . $check["mime"] . ".";
            $uploadOk = 1;
        } else {
            echo "File is not an image.";
            $uploadOk = 0;
        }

// Check if file already exists
if (file_exists($target_file)) {
    echo "Sorry, file already exists.";
    $uploadOk = 0;
}

// Check file size
if ($_FILES[image]["size"] > 500000) {
    echo "Sorry, your file is too large.";
    $uploadOk = 0;
}

// Allow certain file formats
if($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg"
&& $imageFileType != "gif" ) {
    echo "Sorry, only JPG, JPEG, PNG & GIF files are allowed.";
    $uploadOk = 0;
}

// Check if $uploadOk is set to 0 by an error
if ($uploadOk == 0) {
    echo "Sorry, your file was not uploaded.";

// if everything is ok, try to upload file
} else {
    move_uploaded_file($_FILES[image]["tmp_name"], $target_file);
    echo "The file ". basename( $_FILES[image]["name"]). " has been uploaded.";
    } //else {
        //echo "Sorry, there was an error uploading your file. Please try again.";
    //}
}
 
?>

<form class="form-group" action="upload.php" method="post" enctype="multipart/form-data">
                Select image to upload:
                <label for="image">Image</label>
                <input type="file" name="myfile" id="image"/>
                <input type="submit" value="Upload Image" name="btn-img">
                <!-- <input type="image" name="image" value=" <?php //if ( isset($_POST['image']) ) echo $_POST['image']; ?>"> -->
            </form>