<?php

//RW
//require_once '../../model/connection.php';

$newFileName = '';

if (isset ($_POST['btn-post'])) {
    
  // var_dump($_FILES);
  // var_dump($_POST);

// Check if image file is a actual image or fake image

    
    if (($_FILES["image"]['name']) != "") {
        $temp = explode(".", $_FILES["image"]["name"]);
        $uniqueSaveName=time().uniqid(rand());
        $newFileName = $uniqueSaveName .  '.' . end($temp);
       
        $target_dir = "../Model/blogimageuploads/";
        $target_file = $target_dir . $newFileName;
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file,PATHINFO_EXTENSION);
        $check = getimagesize($_FILES["image"]["tmp_name"]);
        if($check !== false) {
            $uploadOk = 1;
        } else {
            $uploadOk = 0;
        }

        // Check file size
        if ($_FILES["image"]["size"] > 500000) {
        echo "Sorry, your file is too large.";
        $uploadOk = 0;
        }

        // Allow certain file formats
        if($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg"
        && $imageFileType != "gif" ) {
        echo "Sorry, only JPG, JPEG, PNG & GIF files are allowed.";
        $uploadOk = 0;
        }

        // Check if $uploadOk is set to 0 by an error
        if ($uploadOk == 0) {
        echo "Sorry, your file was not uploaded.";
        }
    
        else {
        move_uploaded_file($_FILES["image"]["tmp_name"], $target_file);
        }
        }
    
        //getting rid of whitespace
    $title     = trim($_POST['title']);
    $content   = trim($_POST['content']);
   // $tags      = trim($_POST['tags']);

    if (empty ($title)){
        
        $error[] = "Please enter a title."; 
    }
    
    if (empty($content)) {

        $error[] = "Please enter some text.";
    } 
    
    if (strlen($title) > 250) {
    $errors = 'Please shorten your title, it is too long (250 character limit).';
    }
    
    if (strlen($content) > 2000) {
    $errors = 'Please shorten your blog post, it is too long (2000 character limit).';
    }

    else {
        $post->newPost($title, $content, $newFileName);
    }
}

?>
<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        
        <style> 
            label {display: block}
        </style>
        
        <title> Add Post </title>
    </head>

    <body>
        <?php echo Controllers\display\display('add_post'); ?>
    </body>
    