
 <?php 
 
require_once '../model/connection.php';
include 'templates/userFunctions.php';
?>

<?php
/*
$newFileNamebio = '';

if (isset ($_POST['btn-post'])) {
    
  // var_dump($_FILES);
  // var_dump($_POST);

// Check if image file is a actual image or fake image

    
    if (($_FILES["image"]['name']) != "") {
        $temp = explode(".", $_FILES["image"]["name"]);
        $uniqueSaveNamebio=time().uniqid(rand());
        $newFileNamebio = $uniqueSaveNamebio .  '.' . end($temp);
       
        $target_dir = "../Model/userdisplaypicture/";
        $target_file = $target_dir . $newFileName;
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file,PATHINFO_EXTENSION);
        $check = getimagesize($_FILES["image"]["tmp_name"]);
        if($check !== false) {
            $uploadOk = 1;
        } else {
            $uploadOk = 0;
        }

        // Check file size
        if ($_FILES["image"]["size"] > 500000) {
        echo "Sorry, your file is too large.";
        $uploadOk = 0;
        }

        // Allow certain file formats
        if($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg"
        && $imageFileType != "gif" ) {
        echo "Sorry, only JPG, JPEG, PNG & GIF files are allowed.";
        $uploadOk = 0;
        }

        // Check if $uploadOk is set to 0 by an error
        if ($uploadOk == 0) {
        echo "Sorry, your file was not uploaded.";
        }
    
        else {
        move_uploaded_file($_FILES["image"]["tmp_name"], $target_file);
        }
        }
}
   */ ?>

<!DOCTYPE html>

<div class='form-group'>
    <form class='form-control' action="" method="post" enctype="multipart/form-data">
                    <label for="image">Image</label>
                    <input type='file' name='image'/>
                    <input type="submit" value="Upload Image" name="btn-img">
    </form>
</div>