<?php
/*Creating a variable that calls the read user method in the post class. 
 * This method will bring up the posts for a certain user based on the id provided from the get in the URL.
 * This code will then echo the Title, Content and Date Posted, in that order. 
 */

$sanitizedID = filter_input(INPUT_GET, 'id',FILTER_SANITIZE_ENCODED);
$posts = $post->viewPost($sanitizedID);
$userID = $posts[4];
$thisUser = $user->getUsername($userID);
?>
<div class="panel panel-default">
    <div class="panel-heading">
      <b><?= strip_tags($posts[1]);?></b> by <a href="viewUser.php?id=<?= $userID ?>"><?=$thisUser[0]?></a>
    </div>
    <div class="panel-body">
        <?php if($posts['image'] != NULL) { ?>
            <a href="../model/blogimageuploads/<?=$posts['image'];?>" target="_blank"><img src="../model/blogimageuploads/<?=$posts['image'];?>" width="150" class="img-thumbnail img-responsive pull-left img-rightmargin" /></a>
            <?php } ?>
    <?= strip_tags($posts[2], '<br><b><i>');?>
    </div>
    <div class='panel-footer'>
        <?php if($posts['tags'] != ''){
            
            $tagsArray=explode(',',$posts['tags']); 
            foreach ($tagsArray as $tag){
                ?> <a href="search.php?tag=<?= $tag; ?>"> <button type="button" class="btn btn-success btn-sm"><?= strip_tags($tag); ?></button></a><?php echo " ";
            }
        }
        ?>
    </div>
</div>
<span class="badge">
<?= $posts[3];?>
</span><br><br>
