<?php
/*Creating a variable that calls the read user method in the post class. 
 * This method will bring up the posts for a certain user based on the id provided from the get in the URL.
 * This code will then echo the Title, Content and Date Posted, in that order. 
 */

$sanitizedID = filter_input(INPUT_GET, 'id',FILTER_SANITIZE_ENCODED);
$posts = $post->readUser($sanitizedID);

foreach($posts as $post):?>
 
<div class="panel panel-default">
  <div class="panel-heading">
      <a href="viewPost.php?id=<?= $post[0]; ?>"><?= $post[1];?></a>
</div>
<div class="panel-body">
<?= $post[2];?>
</div>
</div>
<span class="badge">
<?= $post[3];?>
</span><br><br>
<?php endforeach; ?>