<?php 
if(file_exists("../Model/profileimageuploads/{$randomUserID}.jpg")): ?>
<img class='img-rounded img-responsive pull-left img-rightmargin' src="../Model/profileimageuploads/<?=$randomUserID?>.jpg" width="150" height="150" />
        <?php else: ?>
		<img class='img-rounded img-responsive pull-left img-rightmargin' src="../Model/blogimages/defaultprofile.jpg" width="150" height="150" />
        <?php endif ?>