<?php
/*Creating a variable that calls the read user method in the post class. 
 * This method will bring up the posts for a certain user based on the id provided from the get in the URL.
 * This code will then echo the Title, Content and Date Posted, in that order. 
 */

$sanitizedID = filter_input(INPUT_GET, 'id',FILTER_SANITIZE_ENCODED);
$posts = $post->readUser($sanitizedID);

foreach($posts as $post):?>
 
<div class="panel panel-default">
  <div class="panel-heading">
      <a href="viewPost.php?id=<?= $post['post_id']; ?>"><b><?= htmlspecialchars($post['post_title']);?></b></a>
  </div>
    <div class="panel-body">
        
        <?php if($post['image'] != NULL) { ?>
        <a href="../Model/blogimageuploads/<?=$post['image'];?>" target="_blank"><img src="../Model/blogimageuploads/<?=$post['image'];?>" width="150" class="img-thumbnail img-responsive pull-left img-rightmargin" /></a>
        <?php } ?>
<?= htmlspecialchars($post['post_content']);?>
    </div>
    <div class='panel-footer'>
        <?php if($post['tags'] != ''){
            
            $tagsArray=explode(',',$post['tags']); 
            foreach ($tagsArray as $tag){
                ?> <a href="search.php?tag=<?= $tag; ?>"> <button type="button" class="btn btn-success btn-sm"><?= htmlspecialchars($tag); ?></button></a><?php echo " ";
            }
        }
        ?>
    </div>
</div>
<span class="badge"> 
<?= $post[3];?>
</span><br><br>
 
<?php endforeach; ?>